### ISSUE TITLE
Question: Is there a FAQs? What am I missing?

### ISSUE THREAD

**Issue by wiiNinja** [jenkinsci/scm-filter-aged-refs-plugin#25]
Per documentation, I should find the "Aged refs filtering strategy" behavior after adding the plugin, but finding none when creating a new multi-branch pipeline. I'm just wondering if there's supposed to be some additional configuration that's needed or prerequisite that's needed to be done before I can get the option. 
I am currently using a private Bitbucket Server.

**Comment by ryancurrah** [comment]
I have a PR that will make this plugin usable with Bitbucket Server https://github.com/jenkinsci/scm-filter-aged-refs-plugin/pull/26, and more configurable to boot!

**Comment by TobiX** [comment]
The strategy should be available even without @ryancurrah's changes. The screenshots are quite outdated, since the trait was renamed to "Filter by ref age" in https://github.com/jenkinsci/scm-filter-aged-refs-plugin/commit/74694df813da4d677fd909ba877ce4027abdd960 (2019)
